### ISSUE TITLE
Tests fail on Debian buster/bullseye and Ubuntu focal

### ISSUE THREAD

**Issue by mbanck** [dalibo/check_patroni#51]
The tests fail on Debian oldstable (bullseye):

```
I: pybuild base:232: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9/build; python3.9 -m unittest discover -v 
tests.test_api (unittest.loader._FailedTest) ... ERROR
tests.test_cluster_config_has_changed (unittest.loader._FailedTest) ... ERROR
tests.test_cluster_has_leader (unittest.loader._FailedTest) ... ERROR
tests.test_cluster_has_replica (unittest.loader._FailedTest) ... ERROR
tests.test_cluster_has_scheduled_action (unittest.loader._FailedTest) ... ERROR
tests.test_cluster_is_in_maintenance (unittest.loader._FailedTest) ... ERROR
tests.test_cluster_node_count (unittest.loader._FailedTest) ... ERROR
tests.test_node_is_alive (unittest.loader._FailedTest) ... ERROR
tests.test_node_is_leader (unittest.loader._FailedTest) ... ERROR
tests.test_node_is_pending_restart (unittest.loader._FailedTest) ... ERROR
tests.test_node_is_primary (unittest.loader._FailedTest) ... ERROR
tests.test_node_is_replica (unittest.loader._FailedTest) ... ERROR
tests.test_node_patroni_version (unittest.loader._FailedTest) ... ERROR
tests.test_node_tl_has_changed (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests.test_api (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_api
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9/build/tests/test_api.py", line 2, in <module>
    from pytest_mock import MockerFixture
ImportError: cannot import name 'MockerFixture' from 'pytest_mock' (/usr/lib/python3/dist-packages/pytest_mock.py)
[...]
```

As bullseye is still widely in use, it would be nice if the tests could be adjusted to pass there.

They also fail in the same way on buster and focal, but those are probably less relevant:
https://pgdgbuild.dus.dg-i.net/job/check-patroni-binaries/1/

**Comment by blogh** [comment]
Hi,

@dlax is working on adding an http server to the tests.
It will allow for a better test coverage and ditch the mocker thing all together.

**Comment by dlax** [comment]
This got closed by #55, but I'm not sure it's actually sufficient (although the original error indeed disappeared). In fact, check_patroni depends on click>=8.0.1 whereas bullseye has click 7.1.2 so I'm afraid this would be problematic as well.

@mbanck, are you able to try again with the `master` branch (or the `bullseye` one since I found another issue with old pytest)?

**Comment by dlax** [comment]
> check_patroni depends on click>=8.0.1 whereas bullseye has click 7.1.2

In fact, as far as the test suite is concerned, we appear to support 7.1.2.

**Comment by dlax** [comment]
Went further on this issue and submitted #59, which brings compatibility with bullseye and focal.

**Comment by dlax** [comment]
Are you sure the test suite is run?

https://pgdgbuild.dus.dg-i.net/job/check-patroni-binaries/3/architecture=amd64,distribution=bullseye/console shows:
> 09:44:38 I: pybuild base:232: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9/build; python3.9 -m unittest discover -v 
> 09:44:38 
> 09:44:38 ----------------------------------------------------------------------
> 09:44:38 Ran 0 tests in 0.000s

Or maybe I'm not looking at the right place?

**Comment by mbanck** [comment]
No you're right, they were not run, sigh.

And now that  I managed to run them, they fail all over the place due to #54 and #58

**Comment by blogh** [comment]
Hi, do they pass now ?
