### ISSUE TITLE
Version 3.7 with arch x64 not found

### ISSUE THREAD

**Issue by blogh** [dalibo/check_patroni#74]
```
Run actions/setup-python@v2
Version 3.7 was not found in the local cache
Error: Version 3.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by dlax** [comment]
Python 3.7 is no longer supported; even Python 3.8 has reached end-of-line this month: https://peps.python.org/pep-0569/.

Probably best to just move to 3.9, unless there's a compelling (i.e. someone paying for this) reason to keep support for old Python version.
